config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
      if @restaurant.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new
      end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, :label => 'Enter the name of the restaurante' %>
  <%= f.input :address, :label => 'Where is the restaurant?' %>
  <%= f.input :phone_number, :label => 'What is its phone number?' %>
  <%= f.input :category, :label => 'Which type of food?' %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Les restaurants</h1>

<%= link_to 'Add a new restaurant', new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
<h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.category %></p>

  <%= link_to 'See the details', restaurant_path(restaurant) %>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, :label => 'Enter the name of the restaurante' %>
  <%= f.input :address, :label => 'Where is the restaurant?' %>
  <%= f.input :phone_number, :label => 'What is its phone number?' %>
  <%= f.input :category, :label => 'Which type of food?' %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class=”container”>
  <div class=”row”>
    <div class=”col-6 offset-3”>
      <p id=”notice”><%= notice %></p>
      <p>
        <strong>Name:</strong>
        <%= @restaurant.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @restaurant.address %>
      </p>

      <p>
        <strong>phone_number:</strong>
        <%= @restaurant.phone_number %>
      </p>

      <p>
        <strong>Categiry:</strong>
        <%= @restaurant.category %>
      </p>

      <h5>Reviews</h5>
      <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item">
          <%= review.content %>
        </li>
      <% end %>
      </ul>

      <%= simple_form_for ([ @restaurant, @review ]) do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "Submit review", class: "btn btn-primary" %>
      <% end %>

      <%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %>
    </div>
  </div>
</div>